version: '3'


services:

  # website:
  #   image: httpd:2.4
  #   volumes:
  #     - "./public:/usr/local/apache2/htdocs"
  #   # ports: ["80:80"]
  #   environment:
  #     PHP_XDEBUG: 1
  #     PHP_XDEBUG_MODE: debug
  #     PHP_IDE_CONFIG: serverName=my-ide
  #     PHP_XDEBUG_IDEKEY: "vscode"
  #     PHP_XDEBUG_CLIENT_HOST: kubernetes.docker.internal
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.web.rule=Host(`${PROJECT_BASE_URL}`)"
  #     - "traefik.http.services.web.loadbalancer.server.port=80"

  website:
    build: .
    # image: httpd:2.4
    # image: php:7.4-apache
    # volumes:
    #   - "./public:/usr/local/apache2/htdocs"
    volumes:
      - "./public:/var/www/html"
    # ports: ["80:80"]
    environment:
      PHP_XDEBUG: 1
      PHP_XDEBUG_MODE: debug
      PHP_IDE_CONFIG: serverName=my-ide
      PHP_XDEBUG_IDEKEY: "vscode"
      PHP_XDEBUG_CLIENT_HOST: kubernetes.docker.internal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`${PROJECT_BASE_URL}`)"
      - "traefik.http.services.web.loadbalancer.server.port=80"
    env_file:
      - ".env"

  db:
    # image: mariadb
    # environment:
    #   - MARIADB_ROOT_PASSWORD=admin
    #   - MARIADB_DATABASE=test
    #   - MARIADB_USER=user
    #   - MARIADB_PASSWORD=admin
    # restart: always
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    environment:
      PMA_ARBITRARY: 1
    restart: always
    # ports: ["8080:80"]
    labels:
      # - "traefik.enable=true"
      - "traefik.http.routers.db.rule=Host(`phpmyadmin.${PROJECT_BASE_URL}`)"
      - "traefik.http.services.db.loadbalancer.server.port=80"

  traefik:
    image: traefik:v2.3
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
