version: '3'


services:

  website:
    build: .
    ports: ["80:80"]
    environment:
      PHP_XDEBUG: 1
      PHP_XDEBUG_MODE: debug
      PHP_IDE_CONFIG: serverName=my-ide
      PHP_XDEBUG_IDEKEY: "vscode"
      PHP_XDEBUG_CLIENT_HOST: kubernetes.docker.internal

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_PASSWORD: admin
      MYSQL_USER: admin
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    environment:
      PMA_ARBITRARY: 1
    restart: always
    ports: ["8081:80"]
